-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg3Qwx9GA4ydMDQuAa
JXZMkNOyFoIc1X2QgDrHaIAT5EKgCgYIKoZIzj0DAQehRANCAARJwU6SWvutaq9r
KsqLMa+WmwoZr8lsDW11T6uvlEajRCLfhCEn16Gfw3cwjeKoW+8F6zKl5qtaW0b9
HeDYqcV+
-----END PRIVATE KEY-----