<?php defined('SYSPATH') or die("No direct access allowed");
define("TABLE_PREFIX","");
define("PEOPLE",TABLE_PREFIX."people");
define("SITEINFO",TABLE_PREFIX."siteinfo");
define("CMS",TABLE_PREFIX."cms");
define("COMPANY",TABLE_PREFIX."company");
define("TAXI",TABLE_PREFIX."taxi");
define("MOTORCOMPANY",TABLE_PREFIX."motor_company");
define("MOTORMODEL",TABLE_PREFIX."motor_model");
define("MANAGEFIELD",TABLE_PREFIX."manage_field");
define("ADDFIELD",TABLE_PREFIX."taxi_additional_field");
define("PACKAGE",TABLE_PREFIX."package");
define("COUNTRY",TABLE_PREFIX."country");
define("CITY",TABLE_PREFIX."city");
define("TAXIMAPPING",TABLE_PREFIX."taxi_driver_mapping");
define("PAYMENT_GATEWAYS",TABLE_PREFIX."payment_gateways");
define("RATING",TABLE_PREFIX."rating");
define("PACKAGE_REPORT",TABLE_PREFIX."package_report");
define("SMTP_SETTINGS",TABLE_PREFIX."smtp_settings");
define("STATE",TABLE_PREFIX."state");
define("CONTACTS",TABLE_PREFIX."contacts");
define("PASSENGERS",TABLE_PREFIX."passengers");
define("PASSENGERS_LOG",TABLE_PREFIX."passengers_log");
define("DRIVER",TABLE_PREFIX."driver");
define("MENU",TABLE_PREFIX."menu");
define("UNAVAILABILITY",TABLE_PREFIX."unavailability");
define("COUNT_HISTORY",TABLE_PREFIX."driver_count_history");
define("TRANS",TABLE_PREFIX."transacation");
define("MILES",TABLE_PREFIX."miles");
define("DRIVERBREAKSERVICE",TABLE_PREFIX."driver_break_service");
define("REQUEST_FUND",TABLE_PREFIX."request_fund");
define("WITHDRAW_TRANSACTION_DETAILS",TABLE_PREFIX."withdraw_transaction_details");
define("PAYMENT_MODULES",TABLE_PREFIX."payment_modules");
define("COMPANY_PAYMENT_MODULES",TABLE_PREFIX."company_payment_module");
define("SMS_TEMPLATE",TABLE_PREFIX."sms_template");//
define("DRIVERSHIFTSERVICE",TABLE_PREFIX."driver_shift_history");
define("COMPANYINFO",TABLE_PREFIX."companyinfo");
define("COMPANY_CMS",TABLE_PREFIX."company_cms");
define("RECURR_BOOKING",TABLE_PREFIX."recurr_booking");
define("FREQUENT_LOCATION",TABLE_PREFIX."frequent_location");
define("FREQUENT_JOURNEY",TABLE_PREFIX."frequent_journey");
define("LOGS",TABLE_PREFIX."logs");
define("TBLGROUPACCOUNT",TABLE_PREFIX."grp_account_tbl");
define("TBLGROUP",TABLE_PREFIX."grp_tbl");
define("TBLALGORITHM",TABLE_PREFIX."dispatch_algorithm");
define("COMPANY_MODEL_FARE",TABLE_PREFIX."company_model_fare");
define("PASSENGERS_CARD_DETAILS",TABLE_PREFIX."passengers_creditcard_details");
define("PASSENGERS_REF_DETAILS",TABLE_PREFIX."passengers_referral_list");
define("PASSENGERS_FAV",TABLE_PREFIX."passengers_favourites");
define("PASSENGERS_FAQ",TABLE_PREFIX."passenger_faq");//
define("DRIVER_REF_DETAILS",TABLE_PREFIX."driver_referral_list");//expense_type
define("EXP_TYPE",TABLE_PREFIX."expense_type");
define("DRIVER_EXP",TABLE_PREFIX."driver_expense");
define("DRIVER_TARGET",TABLE_PREFIX."driver_target");
define("DRIVER_REJECTION",TABLE_PREFIX."driver_rejection_list");
define("GET_FREE_QUOTES",TABLE_PREFIX."get_free_quotes");
define("SMS_SETTINGS",TABLE_PREFIX."company_sms_settings");
define("DRIVER_LOCATION_HISTORY",TABLE_PREFIX."driver_location_history");
define("PASSENGER_LOG_TEMP",TABLE_PREFIX."passengers_log_temp");
define("DRIVER_REQUEST_DETAILS",TABLE_PREFIX."driver_request_details");
define("PASSENGER_PROMO",TABLE_PREFIX."passengers_promo");
define("PASSENGER_REFERRAL",TABLE_PREFIX."passenger_referral");
define("PASSENGER_WALLET_LOG",TABLE_PREFIX."passengers_wallet_log");
define("DRIVER_INFO",TABLE_PREFIX."driver_info");
define("LANGUAGE_OPTION",TABLE_PREFIX."language_option");
define("LANGUAGE",TABLE_PREFIX."language");
define("COMPANY_CMS_LANGUAGE",TABLE_PREFIX."company_cms_language");

//MongoDB Collection Names
//$mongodb = new MongoClient("mongodb://104.197.36.40:27017"); //local mongo db config

/*$mongodb = new MongoClient("mongodb://10.128.0.3:27020"); //local mongo db config
$taxi_db = $mongodb->selectDB('GrandLimoDemo');

define("MDB_CONNECTION",$mongodb);
define("MDB_DATABASE",$taxi_db);*/
define("MDB_CMS","cms_menu");
define("MDB_CONTACTS","contacts");
define("MDB_CSC","csc");
define("MDB_COMPANY","company");
define("MDB_DISPATCH_ALGORITHM","dispatch_algorithm");
define("MDB_DRIVER_INFO","driver_driverinfo");
define("MDB_LOCATION_HISTORY","driver_location_history");
define("MDB_REJECTION_HISTORY","driver_rejection_list");
define("MDB_REQUEST_HISTORY","driver_request_details");
define("MDB_SHIFT_HISTORY","driver_shift_history");
define("MDB_LOGS","logs");
define("MDB_MOTOR_MODEL","motor_model");
define("MDB_PACKAGE","package");
define("MDB_COUPON_PACKAGE","coupon_package");
define("MDB_PACKAGE_REPORT","package_report");
define("MDB_PASSENGERS","passengers");
define("MDB_PASSENGERS_FAVOURITES","passengers_favourites");
define("MDB_PASSENGERS_LOGS","passengers_log");
define("MDB_PASSENGERS_LOGS_TEMP","passengers_log_temp");
define("MDB_PASSENGERS_PROMO","passengers_promo");
define("MDB_PASSENGER_REFERRAL","passengers_referral");
define("MDB_PAYMENT_TYPES","payment_gateway_types");
define("MDB_PAYMENT_GATEWAYS","payment_gateways");
define("MDB_PAYMENT_MODULES","payment_modules");
define("MDB_PEOPLE","people");
define("MDB_SITEINFO","siteinfo");
define("MDB_SMS_TEMPLATES","sms_template");
define("MDB_SMTP_SETTINGS","smtp_settings");
define("MDB_TAXI","taxi");
define("MDB_TAXI_DRIVER_MAPPING","taxi_driver_mapping");
define("MDB_TRANSACTION","transaction");
define("MDB_CHILD_ACCOUNT_TYPE","child_account_type");
define("MDB_CHILD_REQUEST_TYPE","child_request_details");
define("MDB_DRIVER_FEEDBACK","driver_feedback");
define("MDB_PAY_BY","pay_by");
define("MDB_NOTIFICATIONS","notifications");
define("MDB_NOTIFICATIONS_TYPE","notifications_type");
define("MDB_TAXI_SERVICE_RANGE","taxi_service_range");
define("MDB_SLIDER_SETTINGS","slider_settings");
define("MDB_PASSENGERSLOGS_CANCELLED","passengers_log_cancelled");
define("MDB_PASSENGERSLOGS_COMPLETED","passengers_log_completed");
define("MDB_PASSENGERSLOGS_MISSED","passengers_log_missed");
define("MDB_PASSENGERSLOGS_REJECTED","passengers_log_rejected");

define("MDB_CARRERS_LIST","careers_list");
define("MDB_RESUMES","careers_resumes");
define("MDB_PASSENGERS_ADDED_PROMO","passengers_added_promocodes");
define("MDB_TESTIMONIAL","testimonial");
define("MDB_WEBSITE_CONTENT","website_content");
define("MDB_WEBSITE_CERTIFICATES","website_certificates");
define("MDB_ZONES","zones");

?>
